name: Release

on:
  push:
    tags: [ "v*" ]

jobs:
  release:
    env:
      AMO_API_KEY: ${{ secrets.AMO_JWT_ISSUER }}
      AMO_API_SECRET: ${{ secrets.AMO_JWT_SECRET }}
      AMO_EXTENSION_ID: ${{ secrets.AMO_EXTENSION_ID }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Build
      run: |
        yarn install
        yarn test
        yarn build
        yarn run pack

    - name: Sign
      run: |
        yarn sign
        yarn generate-update-manifest
 
    - name: Create Release
      uses: meeDamian/github-release@2.0
      with:
        title: "Release ${{ github.ref }}"
        tag: ${{ github.ref }}
        token: ${{ secrets.GITHUB_TOKEN }}
        gzip: false
        files: >
          mh-search-assist.zip:web-ext-artifacts/*.zip
          mh-search-assist.xpi:web-ext-artifacts/*.xpi
          update.json:web-ext-artifacts/update.json
          LICENSE.txt:LICENSE