name: Release

on:
  push:
    tags: [ "v*" ]

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Build
      run: |
        npm ci
        npm test
        npm run build
        npm run pack

    - name: Sign
      run: |
        npm run sign
        npm run generate-update-manifest
      env:
        AMO_API_KEY: ${{ secrets.AMO_JWT_ISSUER }}
        AMO_API_SECRET: ${{ secrets.AMO_JWT_SECRET }}
        AMO_EXTENSION_ID: ${{ secrets.AMO_EXTENSION_ID }}
 
    - name: Create Release
      uses: meeDamian/github-release@2.0
      with:
        title: "Release ${{ github.ref }}"
        tag: ${{ github.ref }}
        token: ${{ secrets.GITHUB_TOKEN }}
        gzip: false
        files: >
          mh-search-assist.zip:web-ext-artifacts/*.zip
          mh-search-assist.xpi:web-ext-artifacts/*.xpi
          update.json:web-ext-artifacts/update.json
          LICENSE.txt:LICENSE